<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>GhostHelmetSticker</AssemblyName>
    <Product>My first plugin</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>GhostHelmetSticker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="BBI.Unity.Game.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="HarmonyX" Version="2.16.1" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.35.1631451" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="BBI.Unity.Game">
      <HintPath>lib\BBI.Unity.Game.dll</HintPath>
    </Reference>
    <Reference Include="Carbon.Localization.Core">
      <HintPath>lib\Carbon.Localization.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
